server:
  port: 0

spring:
  cloud:
    bus:
      enabled: true
      refresh:
        enabled: true
      ack:
        enabled: true
      trace:
        enabled: true
  kafka:
    bootstrap-servers: localhost:9092

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/
      
logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

springdoc:
  packagesToScan: com.epam.carbonbank


test:
  name: ok5

management:
  endpoints:
    web:
      exposure:
        include: "*"
